Untitled Pull Request
etdevios/MovieQuiz-ios pull request #1
Opened 2022-11-19 20:14 UTC by etdevios

Реализован сплеш-скрин и основной экран.

2022-11-20 12:37 UTC, mmbabaev commented
не проставляются нужные шрифты. Заметили ошибку в учебнике, исправим. Нужно тут поставить галочки в таргете
<img width="1368" alt="Screen Shot 2022-11-17 at 00 30 03" src="https://user-images.githubusercontent.com/12600807/202298599-ab0d27f3-bcef-4f62-b236-232b851a0436.png">

2022-11-20 12:37 UTC, mmbabaev commented
шрифты не меняются в приложении. В учебнике допущена ошибка, поэтому этот пункт необязателен. 
На скрине показал как нужно сделать: 
1) Шрифты добавлены в Group (серая папка)
2) Шрифтам проставлена галочка Target Membership  (справа)

<img width="1356" alt="Screen Shot 2022-11-17 at 20 15 01" src="https://user-images.githubusercontent.com/12600807/202513128-d74c5681-7a76-4778-ae5b-0fbcd44f0893.png">

Полезная статья, которая помогла мне разобраться в свое время: 
https://codewithchris.com/common-mistakes-with-adding-custom-fonts-to-your-ios-app/

2022-11-20 12:38 UTC, mmbabaev commented
Не хватает bottom constraint от корневой StackView к SafeArea. После этого проверьте интерфейс на iPhone 13 mini

2022-11-20 12:38 UTC, mmbabaev requested changes

2022-11-20 12:38 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.borderWidth = 8
не хватает округления картинок

2022-11-20 12:38 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.masksToBounds = true
также нужно выставить contentMode = aspectFill

2022-11-20 12:38 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
Необязательно: если быстро нажимать одну и ту же кнопку, то срабатывают лишние нажатия, пока мы ожидаем следующего вопроса. Чтобы этого не было, можно использовать свойство isEnabled. При начале ожидания "выключать" кнопку, после ожидания "включать" https://developer.apple.com/documentation/uikit/uicontrol/1618217-isenabled

2022-11-20 20:21 UTC, mmbabaev commented
Все замечания исправлены, но теперь сжимается label на iphone 13 mini

2022-11-21 13:33 UTC, mmbabaev commented
Интересное решение, принял. Вообще еще можно констрейнты top и bottom здесь уменьшить
<img width="301" alt="Screen Shot 2022-11-21 at 16 32 38" src="https://user-images.githubusercontent.com/12600807/203068417-d3b524b3-66f3-4b81-9b70-b516f507d530.png">

2022-11-30 21:59 UTC, ABashkirova commented
Можно вмержить

2022-12-01 06:49 UTC, merged