Untitled Pull Request
etdevios/MovieQuiz-ios pull request #2
Opened 2022-11-30 20:51 UTC by etdevios

Выполнен 5 спринт

2022-11-30 22:08 UTC, ABashkirova requested changes
Работа не запускается, нужно проверить комплект пулреквеста 🤓 жду апдейт

2022-11-30 22:08 UTC, ABashkirova commented on MovieQuiz/Presentation/AlertPresenter.swift
> +    private func convert(model: QuizResultsViewModel) -> AlertModel {
принято обычно публичные методы раньше приватных объявлять

2022-11-30 22:08 UTC, ABashkirova commented on MovieQuiz/Presentation/AlertPresenter.swift
> +        delegate?.didShow(alert: alert)
Здесь все ок. 

Но на мой взгляд, было бы круче, сразу презентовать алерт на вьюконтроллере (это же презеентер!)

2022-11-30 22:08 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet weak var yesButton: UIButton!
модификаторы приватности не забывай

2022-11-30 22:08 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private var alertPresenter: AlertPresenterProtocol? = nil
Не обязательно инициализировать здесь
```suggestion
    private var alertPresenter: AlertPresenterProtocol? 
```

2022-11-30 22:08 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private var statisticService = StatisticServiceImplementation()
Не соответствует требованиям чек листа

2022-11-30 22:08 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +"""
Хорошо, когда код соблюдает столбчатость.  К сожалению с такими строками автоформаттер не умеет у xcode работать :( 
```suggestion
            Ваш результат \(correctAnswers)/\(questionsAmount)
            Количество сыгранных квизов: \(gamesCount)
            Рекорд: \(bestGames.correct)/\(bestGames.total) (\(bestGames.date.dateTimeString))
            Средняя точность: \(String(format: "%.2f", totalAccuracy))%
            """
```

2022-11-30 22:08 UTC, ABashkirova commented on MovieQuiz/Services/StatisticService.swift
> +            }
UserDefaults поддерживает работу с примитивными типами [для чтения](https://developer.apple.com/documentation/foundation/userdefaults/1407405-integer) и [записи](https://developer.apple.com/documentation/foundation/userdefaults/1413614-set).
Совсем не обязательно простой тип гонять через декодер, когда есть простые способы данные получить/записать.

2022-12-01 07:13 UTC, etdevios commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +"""
Если строки сдвинуть, то на алерте они сместятся, поэтому невозможно отредактировать в столбец

2022-12-01 07:14 UTC, etdevios commented on MovieQuiz/Services/StatisticService.swift
> +            }
Есть простые и проще, но в спринте указан именно этот(

2022-12-01 07:27 UTC, etdevios commented on MovieQuiz/Services/StatisticService.swift
> +            }
Согласен и так же подумал, но у нас дано перечисление, для данных через декодер, тогда зачем мы его указываем?
```suggestion
            private enum Keys: String {
        case correct, total, bestGame, gamesCount
    }
```

2022-12-01 14:26 UTC, etdevios commented on MovieQuiz/Presentation/AlertPresenter.swift
> +        delegate?.didShow(alert: alert)
Так и не смог разобраться, где можно почитать как его сделать или реализовать?

2022-12-01 15:03 UTC, etdevios commented on MovieQuiz/Services/StatisticService.swift
> +            }
исправлено

2022-12-01 15:03 UTC, etdevios commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private var statisticService = StatisticServiceImplementation()
Исправил

2022-12-01 15:03 UTC, etdevios commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private var alertPresenter: AlertPresenterProtocol? = nil
Исправил

2022-12-01 15:03 UTC, etdevios commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet weak var yesButton: UIButton!
Исправил

2022-12-01 15:04 UTC, etdevios commented on MovieQuiz/Presentation/AlertPresenter.swift
> +    private func convert(model: QuizResultsViewModel) -> AlertModel {
исправил

2022-12-01 17:41 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +"""
вообще не должны, но надо посмотреть

2022-12-01 17:48 UTC, ABashkirova commented
Привет!

Смотри на путь до фабрики: он относительный и похоже создан вне проекта. Файл должен лежать внутри директории Services. 
И проект должен его видеть, как и гит :) 
<img width="1512" alt="Снимок экрана 2022-12-01 в 19 42 32" src="https://user-images.githubusercontent.com/20269264/205123922-80ded588-d259-4b79-9ad9-29a99a1677fb.png">

Без этого не сдвинемся с места. 

Обрати внимание еще на то где создаются файлы: они вне рекомендуемых физических директорий. Будет здорово, если это тоже поправишь. 

<img width="524" alt="Снимок экрана 2022-12-01 в 19 43 19" src="https://user-images.githubusercontent.com/20269264/205124107-3c96c590-d720-4169-b2c4-8c87f7a54b04.png">

Не стесняйся просить помощи у Наставника!

2022-12-01 18:00 UTC, etdevios commented
Странно, у меня все нормально( сейчас гляну
<img width="226" alt="image" src="https://user-images.githubusercontent.com/91811325/205126525-40bcf3f6-69f4-43be-969c-e6fe127392a5.png">

2022-12-01 18:22 UTC, ABashkirova commented
> Странно, у меня все нормально( сейчас гляну

ага, у тебя все нормально, потому что файл на твоем компьютере :) а в гите его нет. Очень важно чтобы все файлы были внутри папки исходников проекта)

2022-12-01 18:27 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +"""
@etdevios 
<img width="1197" alt="Снимок экрана 2022-12-01 в 20 26 44" src="https://user-images.githubusercontent.com/20269264/205131554-842125b4-a493-4c1e-85ac-71f48670e4a6.png">

2022-12-01 18:27 UTC, etdevios commented
Да видимо Xcode глюкнул, не трогал файлы после последнего пул реквеста

2022-12-01 18:30 UTC, ABashkirova approved these changes
Принято! Можно мерджить

2022-12-01 18:31 UTC, etdevios commented
Александра, Спасибо! Может еще какие-то пожелания есть? Очень хочется писать хороший код)

2022-12-01 18:33 UTC, merged

2022-12-01 18:43 UTC, etdevios commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +"""
я пробывал, они уезжали.... видимо, что-то пошло не так

2022-12-01 18:46 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +"""
да, важно чтобы три кавычки тоже стояли в том же столбце.

2022-12-01 18:46 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +"""
поэксперементируй)

2022-12-01 18:47 UTC, ABashkirova commented
@etdevios пока все хорошо! если возникает потребность, обязательно пишу :)

2022-12-01 18:52 UTC, etdevios commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +"""
Точно! Когда писал эти строки не обратил внимание где были кавычки, остальной текст смещал) Буду знать, спасибо еще раз!